[package]
name = "mrload/knitt"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Loader = "sleitnick/loader@2.0.0"

Fusion = "acecateer/fusion@0.3.1"

Janitor = "howmanysmall/janitor@1.17.0"
Promise = "evaera/promise@4.0.0"