local ConnectFours = {}

ConnectFours.Chips = { "BlueChip", "RedChip" }

ConnectFours.START_PLAYER = 1
ConnectFours.TURN_COOLDOWN = 1
ConnectFours.TURN_TIME_OUT = 10

ConnectFours.BOARD_COLUMNS = 7
ConnectFours.BOARD_ROWS = 6
ConnectFours.START_COLUMN = 1
ConnectFours.SELECT_COLUMN_MARGIN = 0.1

ConnectFours.BOARD_MODEL_COLUMN_MARGIN = 0.1
ConnectFours.BOARD_MODEL_ROW_MARGIN = 0.13

return ConnectFours