local GlassBridge = {}

GlassBridge.RESET_COOLDOWN = 60
GlassBridge.PLATFORM_RESPAWN_COOLDOWN = 12

GlassBridge.CORRECT_PLATFORM_PER_JUMP = 1

GlassBridge.STUN_PLAYER = true
GlassBridge.STUNNED_DURATION = 1

GlassBridge.SHOW_PATH = false

GlassBridge.TWEEN_INFO = TweenInfo.new(2, Enum.EasingStyle.Quad, Enum.EasingDirection.Out)

GlassBridge.PLATFORM_ROTATE_FORCE_MIN = 1
GlassBridge.PLATFORM_ROTATE_FORCE_MAX = 5

GlassBridge.RESPAWN_HEIGHT = 3

return GlassBridge